name             'wikistats'
maintainer       'Timothy Jones'
maintainer_email 'ti.do.jo@gmail.com'
license          'All rights reserved'
description      'Installs/Configures wikistats'
long_description 'Installs/Configures wikistats'
version          '0.1.0'

depends               'apache2'
depends               'chef-solo-search'
depends 	      'database'
depends               'mysql'
depends		      'python'
